development:
  adapter: postgresql
  encoding: utf8
  database: plan_ahead_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: plan_ahead_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: plan_ahead_production
  pool: 5
  username:
  password: